Feature/1057 implement tables
nccgroup/ScoutSuite pull request #1076
Opened 2021-02-14 03:24 UTC by loic294

# Description

**Make sure the PR is against the `develop` branch (see [Contributing](https://github.com/nccgroup/ScoutSuite/blob/master/CONTRIBUTING.md)).**

Please include a summary of the change(s) and which issue(s) it addresses. Please also include relevant motivation and context.

Fixes # (issue)

## Type of change

Select the relevant option(s):

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works (optional)
- [ ] New and existing unit tests pass locally with my changes

2021-02-14 18:43 UTC, SamuelMeilleur requested changes
![image](https://user-images.githubusercontent.com/26723367/107885774-1e8df100-6eca-11eb-87f6-924b492baadc.png)
About the style:
- The background of the table should be the same as the app rather than white.
- The icons in the severity columns aren't centered (can be done with `display: flex;` and `align-items: center`.

2021-02-14 19:32 UTC, SamuelMeilleur requested changes

2021-02-14 19:54 UTC, loic294 commented on ScoutSuite/frontend/src/components/SeverityLabel/index.js
> +  if (severity === 'critical') {
Yes, totally! Copy/Paste is just so easy sometimes 🥺 I will change it for an object that contains the text/icon.

2021-02-14 19:56 UTC, loic294 commented on ScoutSuite/frontend/src/components/Table/index.js
> +        typeof sortBy[item.key] === 'function'
Oh, good catch! I am supposed to "memoize" the content value if it's a function but had a problem with that so I removed it and forgot to add it back. I will fix that.

2021-02-14 19:59 UTC, loic294 commented
> ![image](https://user-images.githubusercontent.com/26723367/107885774-1e8df100-6eca-11eb-87f6-924b492baadc.png)
> 
> About the style:
> 
> - The background of the table should be the same as the app rather than white.
> 
> - The icons in the severity columns aren't centered (can be done with `display: flex;` and `align-items: center`.

- Not sure to understand the why the background colour would be something else than white? That's what I had in the design. 

- `display: flex;` actually messes up the with of the columns but I will use which is specific for tables 

```
td 
{
    text-align: center; 
    vertical-align: middle;
} 
```

2021-02-17 02:00 UTC, SamuelMeilleur approved these changes

2021-02-17 02:00 UTC, merged