Added dynamic partial import
nccgroup/ScoutSuite pull request #1095
Opened 2021-02-22 23:05 UTC by loic294

# Description

**Make sure the PR is against the `develop` branch (see [Contributing](https://github.com/nccgroup/ScoutSuite/blob/master/CONTRIBUTING.md)).**

Please include a summary of the change(s) and which issue(s) it addresses. Please also include relevant motivation and context.

Fixes # (issue)

## Type of change

Select the relevant option(s):

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works (optional)
- [ ] New and existing unit tests pass locally with my changes

2021-02-22 23:11 UTC, SamuelMeilleur commented on ScoutSuite/frontend/src/pages/FlaggedItems/SelectedItemContainer/index.js
> +  if (l1 || l2 || !data) return null;
c'est quoi le 11, 12?

2021-02-23 00:14 UTC, loic294 commented on ScoutSuite/frontend/src/pages/FlaggedItems/SelectedItemContainer/index.js
> +  if (l1 || l2 || !data) return null;
C'est 'loading1' et 'loading2' comme j'ai deux useAPI

2021-02-23 04:23 UTC, SamuelMeilleur requested changes

2021-02-23 04:23 UTC, SamuelMeilleur commented on ScoutSuite/frontend/src/partials/aws/s3.buckets.id/BucketInformations/index.js
> +    defaultEncryption: PropTypes.bool,
you forgot to also change the variables' name in propTypes.

2021-02-23 04:23 UTC, SamuelMeilleur commented on ScoutSuite/frontend/src/partials/aws/s3.buckets.id/index.js
> +  console.log('DATA', data);
forgot the console.log

2021-02-23 04:41 UTC, SamuelMeilleur approved these changes

2021-02-23 04:46 UTC, merged